# Generated by Django 2.1.5 on 2020-03-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(default='')),
                ('product_image', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
